apiVersion: v1
kind: Pod
metadata:
  name: joker
  labels:
    app: fast-api
spec:
  containers:
    - name: hello-joker
      image: heons/hello-joker:v1
      ports:
        - containerPort: 8083 #애플리케이션이 노출할 포트
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"